### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Wrong line: 3. Available lines count: 3

### ISSUE THREAD

**Issue by sairam4123** [exigow/intellij-gdscript#58]
Plugin version: ```0.26.6```
Exception: ```java.lang.IndexOutOfBoundsException: Wrong line: 3. Available lines count: 3```
Stacktrace:
```text
java.lang.IndexOutOfBoundsException: Wrong line: 3. Available lines count: 3
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:198)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:179)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:996)
	at lsp.PublishDiagnosticsParamsParser.convertToOffset(PublishDiagnosticsParamsParser.kt:36)
	at lsp.PublishDiagnosticsParamsParser.parseRange(PublishDiagnosticsParamsParser.kt:28)
	at lsp.PublishDiagnosticsParamsParser.parse(PublishDiagnosticsParamsParser.kt:20)
	at lsp.LanguageServerService$LocalService$publishDiagnostics$1.run(LanguageServerService.kt:87)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by exigow** [comment]
Thanks @sairam4123, I'll look into it.

**Comment by sairam4123** [comment]
Yours welcome!

**Comment by exigow** [comment]
@sairam4123, fixed. Let me know if there are still some issues with LSP support.

To let you know: I just published a fresh artifact on the marketplace. New version (`v0.30.1`) will be automatically available tomorrow / day after (The plugin update is pending JetBrains approval). If you want to test a new version immediately, you have to clone & build or download the latest artifact (see: readme).

**Comment by sairam4123** [comment]
Oh, I'll wait, till tomorrow or day after tomorrow.
