### ISSUE TITLE
com.intellij.diagnostic.PluginException: Cannot create class api.VersionedClassesService [Plugin: gdscript]

### ISSUE THREAD

**Issue by albemala** [exigow/intellij-gdscript#59]
Plugin version: ```0.30.1```
IDE version: ```AI-193.6911.18.40.6626763```
Exception: ```com.intellij.diagnostic.PluginException: Cannot create class api.VersionedClassesService [Plugin: gdscript]```
Stacktrace:
```text
com.intellij.diagnostic.PluginException: Cannot create class api.VersionedClassesService [Plugin: gdscript]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:406)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:58)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClass(PlatformComponentManagerImpl.kt:496)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.createLightService(PlatformComponentManagerImpl.kt:439)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.access$createLightService(PlatformComponentManagerImpl.kt:44)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl$getOrCreateLightService$$inlined$use$lambda$1.run(PlatformComponentManagerImpl.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:191)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getOrCreateLightService(PlatformComponentManagerImpl.kt:353)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getLightService$intellij_platform_serviceContainer(PlatformComponentManagerImpl.kt:322)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:282)
	at gdscript.lexer.scanner.IdentifierScanner.collectKeywords(IdentifierScanner.kt:63)
	at gdscript.lexer.scanner.IdentifierScanner.recognizeType(IdentifierScanner.kt:28)
	at gdscript.lexer.scanner.IdentifierScanner.scanToken(IdentifierScanner.kt:22)
	at gdscript.lexer.ScriptLexer.advance(ScriptLexer.kt:30)
	at gdscript.lexer.ScriptLexer.start(ScriptLexer.kt:21)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.doSetText(LexerEditorHighlighter.java:430)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:411)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.loadEditorInBackground(TextEditorImpl.java:71)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:44)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$null$0(AsyncEditorLoader.java:93)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$scheduleLoading$1(AsyncEditorLoader.java:91)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:286)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$null$3(NonBlockingReadActionImpl.java:255)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$null$4(NonBlockingReadActionImpl.java:255)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:825)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:71)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:64)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$5(NonBlockingReadActionImpl.java:254)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClass(PlatformComponentManagerImpl.kt:457)
	... 45 more
Caused by: java.lang.NoClassDefFoundError: org/jsoup/Jsoup
	at api.utils.ClassParser.parseXml(ClassParser.kt:11)
	at api.utils.ClassUnzipper.readEntries(ClassUnzipper.kt:25)
	at api.utils.ClassUnzipper.unzip(ClassUnzipper.kt:13)
	at api.VersionedClassesService.loadResource(VersionedClassesService.kt:25)
	at api.VersionedClassesService.<init>(VersionedClassesService.kt:13)
	... 50 more
Caused by: java.lang.ClassNotFoundException: org.jsoup.Jsoup PluginClassLoader[gdscript, 0.30.1] com.intellij.ide.plugins.cl.PluginClassLoader@208f8fcb
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 55 more
```

**Comment by exigow** [comment]
@albemala, thanks for posting this issue and your kind words. :pray: :)

It looks like I forgot to add some dependencies. Update should be available tomorrow.

**Comment by albemala** [comment]
Now it works again, thank you very much!
