### ISSUE TITLE
kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by chunchuna** [exigow/intellij-gdscript#68]
Plugin version: ```0.30.10```
IDE version: ```IU-202.7660.26```
Exception: ```kotlin.KotlinNullPointerException```
Stacktrace:
```text
kotlin.KotlinNullPointerException
	at lsp.PublishDiagnosticsParamsParser.parse(PublishDiagnosticsParamsParser.kt:18)
	at lsp.LanguageServerService$LocalService$publishDiagnostics$1.run(LanguageServerService.kt:87)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by exigow** [comment]
Thanks @chunchuna. At first glance it looks like the error is coming from LSP client.

Please note that current LSP code is very error prone (disabled by default; server is reverse engineered from Godot Engine code because of lack of official documentation) so kudos you for testing this. :blue_heart: 

My question is: what precise version of Godot Engine are you using?

You can check this with `godot --version` command. I might need this to reproduce exception locally.

**Comment by chunchuna** [comment]
I use the latest 3.2.3. The problem I encountered was that I couldn't complete the code automatically. No code can be completed.

**Comment by chunchuna** [comment]
I come from China, so I may not be able to express myself accurately. I can't <<Code completion>>. I have encountered the same situation with the latest version of IntelliJ IDE, and the 2019 IntelliJ IDE. Then I tried to use an earlier version of the gdscript plug-in, but I also couldn't <<Code completion>> .

**Comment by chunchuna** [comment]
I can't Code completion. I tested the latest version of IDE and 2019 IDE. With the same problem, I tried a lower version of the plug-in, but still couldn't Code completion. Maybe it's the version of godot. I have no idea.

**Comment by chunchuna** [comment]
I tested godot 3.2.2 and still couldn't Code completion. And no folding symbols are displayed.

**Comment by chunchuna** [comment]
> Thanks @chunchuna. At first glance it looks like the error is coming from LSP client.
> 
> Please note that current LSP code is very error prone (disabled by default; server is reverse engineered from Godot Engine code because of lack of official documentation) so kudos you for testing this. 💙
> 
> My question is: what precise version of Godot Engine are you using for LSP server?
> 
> You can check this with `godot --version` command. I might need this to reproduce exception locally.

i tested godot 3.2.3 and 3.2.2 . With the same problem.( couldn't Code completion. And no folding symbols are displayed.)
